// Generated by gencpp from file apriltag_ros/AnalyzeSingleImage.msg
// DO NOT EDIT!


#ifndef APRILTAG_ROS_MESSAGE_ANALYZESINGLEIMAGE_H
#define APRILTAG_ROS_MESSAGE_ANALYZESINGLEIMAGE_H

#include <ros/service_traits.h>


#include <apriltag_ros/AnalyzeSingleImageRequest.h>
#include <apriltag_ros/AnalyzeSingleImageResponse.h>


namespace apriltag_ros
{

struct AnalyzeSingleImage
{

typedef AnalyzeSingleImageRequest Request;
typedef AnalyzeSingleImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AnalyzeSingleImage
} // namespace apriltag_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::apriltag_ros::AnalyzeSingleImage > {
  static const char* value()
  {
    return "d60d994450f73cbdba772751d78c9952";
  }

  static const char* value(const ::apriltag_ros::AnalyzeSingleImage&) { return value(); }
};

template<>
struct DataType< ::apriltag_ros::AnalyzeSingleImage > {
  static const char* value()
  {
    return "apriltag_ros/AnalyzeSingleImage";
  }

  static const char* value(const ::apriltag_ros::AnalyzeSingleImage&) { return value(); }
};


// service_traits::MD5Sum< ::apriltag_ros::AnalyzeSingleImageRequest> should match
// service_traits::MD5Sum< ::apriltag_ros::AnalyzeSingleImage >
template<>
struct MD5Sum< ::apriltag_ros::AnalyzeSingleImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::apriltag_ros::AnalyzeSingleImage >::value();
  }
  static const char* value(const ::apriltag_ros::AnalyzeSingleImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::apriltag_ros::AnalyzeSingleImageRequest> should match
// service_traits::DataType< ::apriltag_ros::AnalyzeSingleImage >
template<>
struct DataType< ::apriltag_ros::AnalyzeSingleImageRequest>
{
  static const char* value()
  {
    return DataType< ::apriltag_ros::AnalyzeSingleImage >::value();
  }
  static const char* value(const ::apriltag_ros::AnalyzeSingleImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::apriltag_ros::AnalyzeSingleImageResponse> should match
// service_traits::MD5Sum< ::apriltag_ros::AnalyzeSingleImage >
template<>
struct MD5Sum< ::apriltag_ros::AnalyzeSingleImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::apriltag_ros::AnalyzeSingleImage >::value();
  }
  static const char* value(const ::apriltag_ros::AnalyzeSingleImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::apriltag_ros::AnalyzeSingleImageResponse> should match
// service_traits::DataType< ::apriltag_ros::AnalyzeSingleImage >
template<>
struct DataType< ::apriltag_ros::AnalyzeSingleImageResponse>
{
  static const char* value()
  {
    return DataType< ::apriltag_ros::AnalyzeSingleImage >::value();
  }
  static const char* value(const ::apriltag_ros::AnalyzeSingleImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APRILTAG_ROS_MESSAGE_ANALYZESINGLEIMAGE_H
